CI: try "pull through proxy" go get up to five times
I manually tested this on a local clone of the cue repo.
With a commit that doesn't exist on the remote, I get the 410 retries:

	$ bash test.sh; echo status: $?
	[...]
	got a 410; retrying
	go: cuelang.org/go/cmd/cue@f8fa23b46130e90694de55d5a6365b3079574f3a: invalid version: reading https://proxy.golang.org/cuelang.org/go/cmd/cue/@v/f8fa23b46130e90694de55d5a6365b3079574f3a.info: 410 Gone
		server response: not found: cuelang.org/go/cmd/cue@f8fa23b46130e90694de55d5a6365b3079574f3a: invalid version: unknown revision f8fa23b46130e90694de55d5a6365b3079574f3a
	got a 410; retrying
	giving up after a number of retries
	status: 1

With master, I get a single try that succeeds:

	$ bash test.sh; echo status: $?
	go: creating new go.mod: module test
	go: added cuelang.org/go v0.4.4-0.20220729051708-0a46a1624353
	[...]
	status: 0

With a malformed version like foo/bar, to force a non-410 error,
we fail immediately without retrying:

	$ bash test.sh; echo status: $?
	go: creating new go.mod: module test
	go: cuelang.org/go/cmd/cue@foo/bar: invalid version: version "foo/bar" invalid: disallowed version string
	status: 1

I chose five tries with 1s sleeps in between somewhat arbitrarily.
We can tweak those over time as needed.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: I7c97449e5fbd9eaef0bdd2736212ee79c189ee9b
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/541802
Unity-Result: CUEcueckoo <cueckoo@cuelang.org>
TryBot-Result: CUEcueckoo <cueckoo@cuelang.org>
Reviewed-by: Paul Jolly <paul@myitcv.io>

diff --git a/.github/workflows/trybot.yml b/.github/workflows/trybot.yml
--- a/.github/workflows/trybot.yml
+++ b/.github/workflows/trybot.yml
@@ -78,5 +78,30 @@ jobs:
         run: |-
           v=$(git rev-parse HEAD)
           cd $(mktemp -d)
-          go mod init mod.com
-          GOPROXY=https://proxy.golang.org go get -d cuelang.org/go/cmd/cue@$v
+          go mod init test
+
+          # Try up to five times if we get a 410 error, which either the proxy or sumdb
+          # can return if they haven't retrieved the requested version yet.
+          for i in {1..5}; do
+          	# GitHub Actions defaults to "set -eo pipefail", so we use an if clause to
+          	# avoid stopping too early. We also use a "failed" file as "go get" runs
+          	# in a subshell via the pipe.
+          	rm -f failed
+          	if ! GOPROXY=https://proxy.golang.org go get cuelang.org/go/cmd/cue@$v; then
+          		touch failed
+          	fi |& tee output.txt
+
+          	if [[ -f failed ]]; then
+          		if grep -q '410 Gone' output.txt; then
+          			echo "got a 410; retrying"
+          			sleep 1s # do not be too impatient
+          			continue
+          		fi
+          		exit 1 # some other failure; stop
+          	else
+          		exit 0 # success; stop
+          	fi
+          done
+
+          echo "giving up after a number of retries"
+          exit 1
